name: noso_rest_api
description: "Implementing noso rest-api calls"
version: 0.0.2
publish_to: none
homepage: "https://api.nosocoin.com/docs/#/"

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  http: ^1.2.1
  json_serializable: ^6.8.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.9

  

